config/routes.rb
Rails.application.routes.draw do
  # Routes for resources
  resources :sales
  resources :clients

  # Routes for Devise
  devise_for :users, skip: :registrations, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  resources :users do
    patch :block, on: :member
    patch :unblock, on: :member
  end

  # Routes for products
  resources :products

  # Additional routes
  get "search", to: "home#index"  # Route for search

  # Application health check route (optional)
  get "up" => "rails/health#show", as: :rails_health_check

  # Define the root of the application
  root "products#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Avivas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/images/logo.webp" type="image/webp">
    <link rel="apple-touch-icon" href="/images/logo.webp">
    <link rel="preload" href="/assets/application-e98745be.js" as="script">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul class="navbar">
      <li class="left">
        <% if current_user %>
        <%= link_to "Mi cuenta", edit_user_path(current_user) %>
        <% end %>
      </li>
      <div class="center">
        <% if can? :read, Product %>
        <li><%= link_to 'Productos', products_path %></li>
        <% end %>
        <% if can? :read, Sale %>
        <li><%= link_to 'Ventas', sales_path %></li>
        <% end %>
        <% if can? :read, User %>
        <li><%= link_to 'Usuarios', users_path %></li>
        <% end %>
      </div>
      <li class="right">
        <% if current_user %>
        <%= link_to "Cerrar sesión", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "¿Está seguro de que desea cerrar sesión?" } %>
        <% else %>
        <%= link_to "Iniciar sesión", new_user_session_path %>
        <% end %>
      </li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

<style>
  body {
    font-family: Arial, sans-serif;
  }


  .navbar {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #99cc99;
    display: flex;
    justify-content: space-between;
  }

  .navbar .center {
    display: flex;
    justify-content: center;
    flex-grow: 1;
  }

  .navbar li {
    float: none;
    font-family: Arial, Helvetica, sans-serif;
  }

  .navbar li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

  .navbar li a:hover {
    background-color: #111;
  }

  .navbar .right {
    margin-left: auto;
  }
</style>